config/routes.rb
Rails.application.routes.draw do

  controller :graphs do
    get 'graphs' => :show, :as => :graph
  end

  controller :pages do
    get '(:span)' => :index, :as => :dashboard
  end

  namespace :api do
    namespace :v1 do
      resources :input, :only => :create
    end
  end

  root :to => 'pages#index'
end

app/models/air_temp.rb
class AirTemp < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/level.rb
class Level < ApplicationRecord
end

app/models/temperature.rb
class Temperature < ApplicationRecord
end

app/models/water_temp.rb
class WaterTemp < ApplicationRecord
end

app/controllers/api/v1/input_controller.rb
module Api
  module V1
    class InputController < ApiController

      def create
        params[:event].classify.constantize.create! :value => params[:data]
        head :ok
      end

    end
  end
end

app/controllers/api_controller.rb
class ApiController < ActionController::Base

  skip_before_action :verify_authenticity_token

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/graphs_controller.rb
class GraphsController < ApplicationController

  def show
    render :json => GraphPresenter.new(params).data
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
    Rails.logger.info "Host: #{request.host}"
    @presenter = DashboardPresenter.new(params)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title Waterfaller
    = csrf_meta_tags
    = csp_meta_tag
    meta(name="viewport" content="width=device-width")
    meta(name="apple-mobile-web-app-capable" content="yes")
    meta(name="apple-mobile-web-app-status-bar-style" content="white")
    link(rel="shortcut icon" href="//#{request.url.split('/')[2]}/favicon.png")
    link(rel="apple-touch-icon" href="/apple-touch-icon.png")
    link(rel="apple-touch-startup-image" href="/apple-touch-icon.png")

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

  body
    = yield

app/views/pages/index.html.slim
.ph3.tc.sans-serif
  .f3.f1-ns.lh-title.mt1.mt4-ns.mb4 How's the Waterfall Doing?

  .mb4.mb3-ns
    span> Last
    - @presenter.spans.each do |span|
      = link_to span.titlecase, dashboard_path(:span => span),
        :class => "f7 f5-ns pv1 ph3 mh2 ba no-underline black #{'b' if @presenter.current_span?(span)}"
  .cf
    .fl.w-100.w-50-ns.ph4-ns.pb4
      .f2.f2-m.f-subheadline-l.ma0.blue
        == number_with_precision @presenter.current_level, :precision => 2
        | "
      = line_chart graph_path(:model => :level, :span => @presenter.span),
        :points => false, :suffix => '"', :min => 5, :max => 12,
        :height => '230px'

    .fl.w-100.w-50-ns.ph4-ns
      .fl.w-50.f2.f2-m.f-subheadline-l.ma0.blue
        == number_with_precision @presenter.current_water_temp, :precision => 1
        | °F
      .fl.w-50.f2.f2-m.f-subheadline-l.ma0.red
        == number_with_precision @presenter.current_air_temp, :precision => 1
        | °F
      = line_chart graph_path(:models => [:water_temp, :air_temp], :span => @presenter.span),
        :points => false, :suffix => '°F', :min => 50, :max => 100,
        :height => '230px'